<?php
define('ELEX_API_CODE_OK', 0);
define('ELEX_API_CODE_UNKNOWN_ERROR', 10001);
define('ELEX_API_CODE_PARAMETER_ERROR', 10002);
define('ELEX_API_CODE_SIGNATURE_ERROR', 10003);
define('ELEX_API_CODE_METHOD_NOT_EXIST', 10004);
?>